# Copyright (C) 2016  tcz717
# 
# This file is part of teos.
# 
# teos is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# teos is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with teos.  If not, see <http://www.gnu.org/licenses/>.
# 

import os
Import("env")
env=env.Clone()
env.Append(
    CPPDEFINES='__is_teos_kernel',
    CCFLAGS=['-ffreestanding','-fbuiltin'],
)

kernel_objs=SConscript(env.subst("arch/$ARCH/SConscript"),exports='env')
kernel_objs.extend(env.Object('kernel/kernel.c'))
kernel_objs.extend(SConscript("interrupt/SConscript",exports='env'))
kernel_objs.extend(SConscript(dirs=["gdb-stub"],exports='env'))

with os.popen(env.subst('../$CC -print-file-name=crtbegin.o')) as crtbegin:
    kernel_objs.append(File(crtbegin.read().strip('\n')))
with os.popen(env.subst('../$CC -print-file-name=crtend.o')) as crtend:
    kernel_objs.append(File(crtend.read().strip('\n')))

Return('kernel_objs')