# Copyright (C) 2016  tcz717
# 
# This file is part of teos.
# 
# teos is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# teos is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with teos.  If not, see <http://www.gnu.crg/licenses/>.
# 

Import("env")

kernal_arch_c=Split("""
boot.S
gdt.c
idt.c
interrupt-entry.S
interrupt.c
pic.c
tty.c
crti.S
crtn.S
debug.c
serial.c
""")
kernal_arch=env.Object(kernal_arch_c)

Return('kernal_arch')