# Copyright (C) 2016  tcz717
# 
# This file is part of teos.
# 
# teos is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# teos is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with teos.  If not, see <http://www.gnu.org/licenses/>.
# 
Import("env is_kernel")
env=env.Clone()
env.Append(
    CPPDEFINES='__is_teos_libc',
)
if is_kernel:
    env.Append(
        CPPDEFINES='__is_teos_kernel',
        CCFLAGS=['-ffreestanding','-fbuiltin'],
    )
name='k' if is_kernel else 'c'

src=Split("""
init/__init_libc.c
stdio/printf.c
stdio/putchar.c
stdio/puts.c
stdlib/abort.c
stdlib/exit.c
string/memcmp.c
string/memcpy.c
string/memmove.c
string/memset.c
string/strlen.c
""")
libc=env.Library(name,src)

Return('libc')
